import SwiftUI

/// Unified tag chip component with multiple display modes.
/// Replaces duplicated tag chip rendering in InboxCard, ItemCardView, and ContentView.
struct TagChip: View {
    let tag: Tag
    var mode: Mode = .display

    enum Mode {
        /// Read-only, solid border
        case display
        /// Dashed border + confirm/dismiss buttons (inbox auto-tags)
        case autoTag(onConfirm: () -> Void, onDismiss: () -> Void)
        /// Solid border + close button (removable)
        case removable(onRemove: () -> Void)
        /// Pill/capsule shape for source cards
        case capsule
    }

    var body: some View {
        switch mode {
        case .display:
            displayChip
        case .autoTag(let onConfirm, let onDismiss):
            autoTagChip(onConfirm: onConfirm, onDismiss: onDismiss)
        case .removable(let onRemove):
            removableChip(onRemove: onRemove)
        case .capsule:
            capsuleChip
        }
    }

    // MARK: - Display

    private var displayChip: some View {
        Text(tag.name)
            .font(.groveTag)
            .foregroundStyle(tag.isAutoGenerated ? Color.textSecondary : Color.textPrimary)
            .padding(.horizontal, 8)
            .padding(.vertical, 3)
            .background(Color.bgCard)
            .clipShape(RoundedRectangle(cornerRadius: 3))
            .overlay(
                RoundedRectangle(cornerRadius: 3)
                    .strokeBorder(
                        style: tag.isAutoGenerated
                            ? StrokeStyle(lineWidth: 1, dash: [3, 2])
                            : StrokeStyle(lineWidth: 1)
                    )
                    .foregroundStyle(tag.isAutoGenerated ? Color.borderTagDashed : Color.borderTag)
            )
    }

    // MARK: - Auto Tag

    private func autoTagChip(onConfirm: @escaping () -> Void, onDismiss: @escaping () -> Void) -> some View {
        HStack(spacing: 3) {
            Text(tag.name)
                .font(.groveTag)
                .foregroundStyle(tag.isAutoGenerated ? Color.textSecondary : Color.textPrimary)

            if tag.isAutoGenerated {
                Button {
                    onConfirm()
                } label: {
                    Image(systemName: "checkmark")
                        .font(.system(size: 8, weight: .bold))
                        .foregroundStyle(Color.textSecondary)
                }
                .buttonStyle(.plain)
                .help("Confirm tag")

                Button {
                    onDismiss()
                } label: {
                    Image(systemName: "xmark")
                        .font(.system(size: 8, weight: .bold))
                        .foregroundStyle(Color.textTertiary)
                }
                .buttonStyle(.plain)
                .help("Remove tag")
            }
        }
        .padding(.horizontal, 8)
        .padding(.vertical, 3)
        .background(Color.bgCard)
        .clipShape(RoundedRectangle(cornerRadius: 3))
        .overlay(
            RoundedRectangle(cornerRadius: 3)
                .strokeBorder(
                    style: tag.isAutoGenerated
                        ? StrokeStyle(lineWidth: 1, dash: [3, 2])
                        : StrokeStyle(lineWidth: 1)
                )
                .foregroundStyle(tag.isAutoGenerated ? Color.borderTagDashed : Color.borderTag)
        )
    }

    // MARK: - Removable

    private func removableChip(onRemove: @escaping () -> Void) -> some View {
        HStack(spacing: 3) {
            Text(tag.name)
                .font(.groveTag)
                .foregroundStyle(Color.textPrimary)
            Button {
                onRemove()
            } label: {
                Image(systemName: "xmark")
                    .font(.system(size: 7, weight: .bold))
                    .foregroundStyle(Color.textTertiary)
            }
            .buttonStyle(.plain)
        }
        .padding(.horizontal, 8)
        .padding(.vertical, 3)
        .background(Color.bgCard)
        .clipShape(RoundedRectangle(cornerRadius: 3))
        .overlay(
            RoundedRectangle(cornerRadius: 3)
                .stroke(tag.isAutoGenerated ? Color.borderTagDashed : Color.borderTag, lineWidth: 1)
        )
    }

    // MARK: - Capsule

    private var capsuleChip: some View {
        Text(tag.name)
            .font(.groveTag)
            .foregroundStyle(tag.isAutoGenerated ? Color.textSecondary : Color.textPrimary)
            .padding(.horizontal, 8)
            .padding(.vertical, 3)
            .background(Color.bgInput)
            .clipShape(Capsule())
    }
}
